### ISSUE TITLE
有些无法获取银行名称

### ISSUE THREAD

**Issue by hedeqiang** [zhuzhichao/bank-card-info#10]
"data": {
        "validated": true,
        "bank": "XJRCU",
        "bankName": "",
        "bankImg": "https://apimg.alipay.com/combo.png?d=cashier&t=XJRCU",
        "cardType": "DC",
        "cardTypeName": "储蓄卡"
    }

**Comment by Runrioter** [comment]
@hedeqiang  `XJRCU` 是 `新疆农村信用社`  推荐查询工具 https://github.com/hexindai/bcbc

**Comment by zhuzhichao** [comment]
@hedeqiang 之前已经更新了 https://github.com/zhuzhichao/bank-card-info/commit/5038f0c755caa38c0dce640ae9ae64eacbca85e5 ，忘记回复你了，不好意思，更新一下包就好了  composer update "zhuzhichao/bank-card-info"

**Comment by zhuzhichao** [comment]
@Runrioter bin  码的方式确实挺方便的，不知道后续更新是否及时。这个 go 版本的还需要另外起一个服务端口，稍显麻烦点。谢谢推荐。

**Comment by Runrioter** [comment]
@zhuzhichao   
* 支持离线命令行查询 
* 会持续更新的（根据我们业务的新数据持续更新）
* 因为最近阿里这个接口会频繁超时所以开源了这个服务

欢迎试用 😃

**Comment by zhuzhichao** [comment]
@Runrioter 

我没发现有超时的情况，可能我们用的是阿里云？哈哈。 

你的这个做一个公共服务还是不错的，如果纯 PHP 内部使用，可以根据你的 bin csv 搞个 PHP 版本的，直接查询。 😄

**Comment by hedeqiang** [comment]
@zhuzhichao  好，马上更新

**Comment by zhuzhichao** [comment]
@hedeqiang 

你的网站报错了。 😅 

http://flarum.laravelcode.cn/

![image](https://user-images.githubusercontent.com/3017759/46119550-158b1f00-c23e-11e8-85a5-515bbf688e1c.png)

**Comment by hedeqiang** [comment]
@zhuzhichao  😃  ,啥鬼，这个错就错了吧，不用他了

**Comment by hedeqiang** [comment]
@zhuzhichao  我又来了，我有一银行卡号，验证失败
应该是 `奎屯国民村镇银行` ，然而返回 `false`
需要银行卡验证，我邮件发给你，毕竟我拿客户的测试

**Comment by hedeqiang** [comment]
@Runrioter   老哥，我刚才那你的也测试了下，也没有获取到

**Comment by Runrioter** [comment]
@hedeqiang  前10位发给我 然后告诉我总长度即可 谢谢

**Comment by zhuzhichao** [comment]
@hedeqiang 你发一下卡号，我测试一下。

**Comment by hedeqiang** [comment]
@Runrioter  @zhuzhichao   6216351230000000012

**Comment by zhuzhichao** [comment]
@hedeqiang 

我用支付宝 app 测试了一下，这个银行确实不支持。考虑手动选择或者输入吧。

![img_3425](https://user-images.githubusercontent.com/3017759/46129850-6e70ac80-c26a-11e8-98cb-9b691919bf11.PNG)

**Comment by hedeqiang** [comment]
@zhuzhichao  嗯，有一个付费接口，云市场的，可以识别
[银行卡归属地查询](https://market.aliyun.com/products/57000002/cmapi011030.html?spm=5176.2020520132.101.11.7b6672186kCtCK#sku=yuncode503000005)
