### ISSUE TITLE
银行卡不存在的时候报错

### ISSUE THREAD

**Issue by fly2006zhao** [zhuzhichao/bank-card-info#11]
支付宝返回的字符串为 gbk 建议增加一下这行代码

![image](https://user-images.githubusercontent.com/5717074/47429477-170e1f80-d7c9-11e8-81f7-0b40d86bf525.png)

**Comment by Runrioter** [comment]
* 没必要的 因为响应里面没有中文 无论是GBK还是UTF-8都兼容ASCII

* 银行卡不存在的你能发出来吗 提供前10位和长度 我可以帮你查

@fly2006zhao

**Comment by zhuzhichao** [comment]
如 @Runrioter  所说，正常情况下不会出现因为编码导致的报错，@fly2006zhao 你可以把 result 里面的内容发出来，帮你看看。

**Comment by fly2006zhao** [comment]
@zhuzhichao 假设我给接口传一个中文的字符串，返回的结果就会包含一个中文的字符串，并且是gbk的
![image](https://user-images.githubusercontent.com/5717074/47961613-73830180-e049-11e8-9f97-087114c1a6b6.png)
![image](https://user-images.githubusercontent.com/5717074/47961618-7e3d9680-e049-11e8-98c9-87d86a25785e.png)
![image](https://user-images.githubusercontent.com/5717074/47961624-8d244900-e049-11e8-95df-973658c3e2a4.png)

**Comment by Runrioter** [comment]
这属于非法输入了 你肯定需要先保证卡号都是数字啊

**Comment by zhuzhichao** [comment]
@fly2006zhao 你的传参问题，这个需要你自己控制一下。
