### ISSUE TITLE
银行信息列表可以更新一下吗

### ISSUE THREAD

**Issue by ashuiccc** [zhuzhichao/bank-card-info#13]
有些银行名称无法识别

**Comment by zhuzhichao** [comment]
@ashuiccc 能举例一下吗？

**Comment by ashuiccc** [comment]
比如说,客户输入的卡号是厦门银行的,但是银行信息列表中没有厦门银行,就无法显示开户行名称

**Comment by ashuiccc** [comment]
当然,这个工作量可能有点大,您后续想完善的话在完善吧

**Comment by zhuzhichao** [comment]
麻烦提供下卡号，我测试一下

**Comment by ashuiccc** [comment]
啊,我这边没有厦门银行的卡号,我搜了下 你那个匹配的银行名称里,没有厦门银行的,因该是信息没有录入进去

**Comment by ashuiccc** [comment]
6230195920060319945 比如这个 不知道是哪个行的

**Comment by ashuiccc** [comment]
阿里云的api可能是识别了
<img width="343" alt="QQ20190711-144751@2x" src="https://user-images.githubusercontent.com/50192266/61028307-f59ea380-a3ea-11e9-8917-e6b619fbd43d.png">这个里面没有

**Comment by Runrioter** [comment]
![image](https://user-images.githubusercontent.com/1078011/61053478-32d15880-a420-11e9-9b1b-8fe3ab1b79dd.png)

@ashuiccc  用 https://github.com/hexindai/bcbc 可以查到

**Comment by ashuiccc** [comment]
> ![image](https://user-images.githubusercontent.com/1078011/61053478-32d15880-a420-11e9-9b1b-8fe3ab1b79dd.png)
> 
> @ashuiccc 用 https://github.com/hexindai/bcbc 可以查到

是我这边扩展包不是最新版本吗?"zhuzhichao/bank-card-info": "^2.1"

**Comment by ashuiccc** [comment]
咱俩用的不是一个东西 好像

**Comment by Runrioter** [comment]
@ashuiccc  是不一样 都是兼容阿里api的用的一样的码 你可以用这个工具查出来补上

**Comment by ashuiccc** [comment]
好的,拿这个扩展包已经停止更新了吗?

**Comment by zhuzhichao** [comment]
@ashuiccc 已经更新了，你更新一下包  2.1.1 已经添加了厦门银行。
