### ISSUE TITLE
南粤银行的编码有误

### ISSUE THREAD

**Issue by hujghc** [zhuzhichao/bank-card-info#4]
<del>"NYNB"      => "广东南粤银行",</del>

"NYBANK"      => "广东南粤银行",

另外，可以在获取银行名称的地方 self::$bankInfo[$result->bank] 增加isset 判断吗，现在没有就直接抛异常了。

**Comment by zhuzhichao** [comment]
谢谢反馈！你的代码已经被合并了。：）

**Comment by zhuzhichao** [comment]
已经更新到最新的 2.0.1 版本了 https://github.com/zhuzhichao/bank-card-info/releases/tag/2.0.1 

感谢你的参与
