### ISSUE TITLE
作者你好,有新的两家银行

### ISSUE THREAD

**Issue by gbcmikeblue** [zhuzhichao/bank-card-info#7]
"ADBC"     => "中国农业发展银行",
"PBOC"     => "中国人民银行"

对,就是这两个,验证一下,支持作者,哈哈

**Comment by zhuzhichao** [comment]
有没有对应的卡号？我这边测试一下

**Comment by gbcmikeblue** [comment]
,好吧,是我ZZ了,中国人民银行和中国农业发展银行豆不发行银行卡,忽略我

**Comment by zhuzhichao** [comment]
@gbcmikeblue 😄
